/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppTeamRouteImport } from './routes/app/team'
import { Route as AppResourcesRouteImport } from './routes/app/resources'
import { Route as AppPlannerRouteImport } from './routes/app/planner'
import { Route as AppFloorMapRouteImport } from './routes/app/floor-map'
import { Route as AppCalendarRouteImport } from './routes/app/calendar'
import { Route as AppBookingsRouteImport } from './routes/app/bookings'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppSplatRouteImport } from './routes/app/$'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppCheckinResourceIdRouteImport } from './routes/app/checkin.$resourceId'
import { Route as AppAdminOfficeBuilderRouteImport } from './routes/app/admin/office-builder'
import { Route as AppAdminAnalyticsRouteImport } from './routes/app/admin/analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppFloorMapRoute = AppFloorMapRouteImport.update({
  id: '/floor-map',
  path: '/floor-map',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppCheckinResourceIdRoute = AppCheckinResourceIdRouteImport.update({
  id: '/checkin/$resourceId',
  path: '/checkin/$resourceId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOfficeBuilderRoute = AppAdminOfficeBuilderRouteImport.update({
  id: '/office-builder',
  path: '/office-builder',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAnalyticsRoute = AppAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/$': typeof AppSplatRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/bookings': typeof AppBookingsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/floor-map': typeof AppFloorMapRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/app/admin/office-builder': typeof AppAdminOfficeBuilderRoute
  '/app/checkin/$resourceId': typeof AppCheckinResourceIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/$': typeof AppSplatRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/floor-map': typeof AppFloorMapRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/team': typeof AppTeamRoute
  '/app': typeof AppIndexRoute
  '/app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/app/admin/office-builder': typeof AppAdminOfficeBuilderRoute
  '/app/checkin/$resourceId': typeof AppCheckinResourceIdRoute
  '/app/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/$': typeof AppSplatRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/bookings': typeof AppBookingsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/floor-map': typeof AppFloorMapRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/app/admin/office-builder': typeof AppAdminOfficeBuilderRoute
  '/app/checkin/$resourceId': typeof AppCheckinResourceIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/$'
    | '/app/admin'
    | '/app/bookings'
    | '/app/calendar'
    | '/app/floor-map'
    | '/app/planner'
    | '/app/resources'
    | '/app/team'
    | '/app/'
    | '/app/admin/analytics'
    | '/app/admin/office-builder'
    | '/app/checkin/$resourceId'
    | '/app/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/$'
    | '/app/bookings'
    | '/app/calendar'
    | '/app/floor-map'
    | '/app/planner'
    | '/app/resources'
    | '/app/team'
    | '/app'
    | '/app/admin/analytics'
    | '/app/admin/office-builder'
    | '/app/checkin/$resourceId'
    | '/app/admin'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/$'
    | '/app/admin'
    | '/app/bookings'
    | '/app/calendar'
    | '/app/floor-map'
    | '/app/planner'
    | '/app/resources'
    | '/app/team'
    | '/app/'
    | '/app/admin/analytics'
    | '/app/admin/office-builder'
    | '/app/checkin/$resourceId'
    | '/app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resources': {
      id: '/app/resources'
      path: '/resources'
      fullPath: '/app/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planner': {
      id: '/app/planner'
      path: '/planner'
      fullPath: '/app/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/floor-map': {
      id: '/app/floor-map'
      path: '/floor-map'
      fullPath: '/app/floor-map'
      preLoaderRoute: typeof AppFloorMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings': {
      id: '/app/bookings'
      path: '/bookings'
      fullPath: '/app/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$': {
      id: '/app/$'
      path: '/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/checkin/$resourceId': {
      id: '/app/checkin/$resourceId'
      path: '/checkin/$resourceId'
      fullPath: '/app/checkin/$resourceId'
      preLoaderRoute: typeof AppCheckinResourceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/office-builder': {
      id: '/app/admin/office-builder'
      path: '/office-builder'
      fullPath: '/app/admin/office-builder'
      preLoaderRoute: typeof AppAdminOfficeBuilderRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/analytics': {
      id: '/app/admin/analytics'
      path: '/analytics'
      fullPath: '/app/admin/analytics'
      preLoaderRoute: typeof AppAdminAnalyticsRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAnalyticsRoute: typeof AppAdminAnalyticsRoute
  AppAdminOfficeBuilderRoute: typeof AppAdminOfficeBuilderRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAnalyticsRoute: AppAdminAnalyticsRoute,
  AppAdminOfficeBuilderRoute: AppAdminOfficeBuilderRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppBookingsRoute: typeof AppBookingsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppFloorMapRoute: typeof AppFloorMapRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCheckinResourceIdRoute: typeof AppCheckinResourceIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppBookingsRoute: AppBookingsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppFloorMapRoute: AppFloorMapRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
  AppCheckinResourceIdRoute: AppCheckinResourceIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
